### ISSUE TITLE
error: 'NUMBER_DB_SEEK' is not a member of 'rocksdb'

### ISSUE THREAD

**Issue by foongws** [mongodb-partners/mongo-rocks#23]
When I try to compile mongo with rocksdb module, i received following errors:

Compiling build/opt/mongo/db/modules/rocks/src/rocks_server_status.o
src/mongo/db/modules/rocks/src/rocks_server_status.cpp: In member function 'virtual mongo::BSONObj mongo::RocksServerStatusSection::generateSection(mongo::OperationContext*, const mongo::BSONElement&) const':
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:184:14: error: 'NUMBER_DB_SEEK' is not a member of 'rocksdb'
             {rocksdb::NUMBER_DB_SEEK, "num-seeks"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:185:14: error: 'NUMBER_DB_NEXT' is not a member of 'rocksdb'
             {rocksdb::NUMBER_DB_NEXT, "num-forward-iterations"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:186:14: error: 'NUMBER_DB_PREV' is not a member of 'rocksdb'
             {rocksdb::NUMBER_DB_PREV, "num-backward-iterations"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:192:14: error: 'ITER_BYTES_READ' is not a member of 'rocksdb'
             {rocksdb::ITER_BYTES_READ, "bytes-read-iteration"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:196:11: error: could not convert '{{NUMBER_KEYS_WRITTEN, "num-keys-written"}, {NUMBER_KEYS_READ, "num-keys-read"}, {<expression error>, "num-seeks"}, {<expression error>, "num-forward-iterations"}, {<expression error>, "num-backward-iterations"}, {BLOCK_CACHE_MISS, "block-cache-misses"}, {BLOCK_CACHE_HIT, "block-cache-hits"}, {BLOOM_FILTER_USEFUL, "bloom-filter-useful"}, {BYTES_WRITTEN, "bytes-written"}, {BYTES_READ, "bytes-read-point-lookup"}, {<expression error>, "bytes-read-iteration"}, {FLUSH_WRITE_BYTES, "flush-bytes-written"}, {COMPACT_READ_BYTES, "compaction-bytes-read"}, {COMPACT_WRITE_BYTES, "compaction-bytes-written"}}' from '<brace-enclosed initializer list>' to 'const std::vector<std::pair<rocksdb::Tickers, std::basic_string<char> > >'
           };
           ^
scons: *** [build/opt/mongo/db/modules/rocks/src/rocks_server_status.o] Error 1
scons: building terminated because of errors.
build/opt/mongo/db/modules/rocks/src/rocks_server_status.o failed: Error 1

I am compiling from a fresh installation Centos 6.5.

**Comment by igorcanadi** [comment]
What is your RocksDB version? These symbols were added in RocksDB 4.1

**Comment by foongws** [comment]
May I know how to get version 4.1?
Should be version 4. When I open HISTORY.md, i saw this .

# Rocksdb Change Log

## 4.0.0 (9/9/2015)
### New Features
* Added support for transactions.  See include/rocksdb/utilities/transaction.h for more info.

I compile the rocksdb from source using the following command:

git clone https://github.com/facebook/rocksdb.git
cd rocksdb
git checkout mongorocks
make static_lib
make install
cd～

**Comment by IslamAbdelRahman** [comment]
@foongws, you can find RocksDB releases here https://github.com/facebook/rocksdb/releases

You can clone a specific branch using this command (4.1 for example)
`git clone --branch 4.1.fb https://github.com/facebook/rocksdb.git`

**Comment by 15astro** [comment]
I still get the same error while compiling mongodb with rocksdb.  Following [this](https://github.com/mongodb-partners/mongo-rocks/tree/5772b2d8074301a2c7bee7e6e075bb7814677604) doc.

**Comment by igorcanadi** [comment]
@15astro that's so weird. Did you try explicitly checking out 4.1 branch, as @IslamAbdelRahman suggested above?

**Comment by 15astro** [comment]
@IslamAbdelRahman : yes 
It still fails..repeatedly.
# install compression libraries (zlib, bzip2, snappy):
sudo apt-get install zlib1g-dev; sudo apt-get install libbz2-dev; sudo apt-get install libsnappy-dev
# get rocksdb
git clone --branch 4.1.fb https://github.com/facebook/rocksdb.git
# compile rocksdb
cd rocksdb; make static_lib; sudo INSTALL_PATH=/usr make install; cd ..
# get mongo
git clone https://github.com/mongodb/mongo.git
# get mongorocks
git clone https://github.com/mongodb-partners/mongo-rocks
# add rocksdb module to mongo
mkdir -p mongo/src/mongo/db/modules/
ln -sf ~/mongo-rocks mongo/src/mongo/db/modules/rocks
# compile mongo
cd mongo; scons mongod

Please help

**Comment by 15astro** [comment]
Below is the stackstace:

In file included from src/mongo/db/modules/rocks/src/rocks_init.cpp:39:0:
src/mongo/db/modules/rocks/src/rocks_engine.h:120:22: error: 'virtual bool mongo::RocksEngine::isEphemeral() const' marked override, but does not override
         virtual bool isEphemeral() const override { return false; }
                      ^
In file included from src/mongo/db/modules/rocks/src/rocks_engine.h:47:0,
                 from src/mongo/db/modules/rocks/src/rocks_init.cpp:39:
src/mongo/db/storage/kv/kv_engine.h:118:18: error: 'virtual bool mongo::KVEngine::isEphemeral()' was hidden [-Werror=overloaded-virtual]
     virtual bool isEphemeral() {
                  ^
In file included from src/mongo/db/modules/rocks/src/rocks_init.cpp:39:0:
src/mongo/db/modules/rocks/src/rocks_engine.h:120:22: error:   by 'virtual bool mongo::RocksEngine::isEphemeral() const' [-Werror=overloaded-virtual]
         virtual bool isEphemeral() const override { return false; }
                      ^
In file included from src/mongo/db/service_context.h:35:0,
                 from src/mongo/db/modules/rocks/src/rocks_init.cpp:33:
src/mongo/db/storage/storage_engine.h:72:32: error: 'virtual mongo::StorageEngine* mongo::StorageEngine::Factory::create(const mongo::StorageGlobalParams&, const mongo::StorageEngineLockFile&) const' was hidden [-Werror=overloaded-virtual]
         virtual StorageEngine* create(const StorageGlobalParams& params,
                                ^
src/mongo/db/modules/rocks/src/rocks_init.cpp:51:36: error:   by 'virtual mongo::StorageEngine* mongo::{anonymous}::RocksFactory::create(const mongo::StorageGlobalParams&, const mongo::StorageEngineLockFile*) const' [-Werror=overloaded-virtual]
             virtual StorageEngine* create(const StorageGlobalParams& params,
                                    ^
src/mongo/db/modules/rocks/src/rocks_init.cpp: In function 'mongo::Status mongo::_mongoInitializerFunction_RocksEngineInit(mongo::InitializerContext*)':
src/mongo/db/modules/rocks/src/rocks_init.cpp:120:95: error: cannot allocate an object of abstract type 'mongo::{anonymous}::RocksFactory'
         getGlobalServiceContext()->registerStorageEngine(kRocksDBEngineName, new RocksFactory());
                                                                                               ^
src/mongo/db/modules/rocks/src/rocks_init.cpp:48:15: note:   because the following virtual functions are pure within 'mongo::{anonymous}::RocksFactory':
         class RocksFactory : public StorageEngine::Factory {
               ^
In file included from src/mongo/db/service_context.h:35:0,
                 from src/mongo/db/modules/rocks/src/rocks_init.cpp:33:
src/mongo/db/storage/storage_engine.h:72:32: note: 	virtual mongo::StorageEngine* mongo::StorageEngine::Factory::create(const mongo::StorageGlobalParams&, const mongo::StorageEngineLockFile&) const
         virtual StorageEngine* create(const StorageGlobalParams& params,
                                ^
Compiling build/opt/mongo/db/modules/rocks/src/rocks_parameters.o
cc1plus: all warnings being treated as errors
scons: *** [build/opt/mongo/db/modules/rocks/src/rocks_init.o] Error 1
In file included from src/mongo/db/modules/rocks/src/rocks_parameters.h:32:0,
                 from src/mongo/db/modules/rocks/src/rocks_parameters.cpp:32:
src/mongo/db/modules/rocks/src/rocks_engine.h:120:22: error: 'virtual bool mongo::RocksEngine::isEphemeral() const' marked override, but does not override
         virtual bool isEphemeral() const override { return false; }
                      ^
In file included from src/mongo/db/modules/rocks/src/rocks_engine.h:47:0,
                 from src/mongo/db/modules/rocks/src/rocks_parameters.h:32,
                 from src/mongo/db/modules/rocks/src/rocks_parameters.cpp:32:
src/mongo/db/storage/kv/kv_engine.h:118:18: error: 'virtual bool mongo::KVEngine::isEphemeral()' was hidden [-Werror=overloaded-virtual]
     virtual bool isEphemeral() {
                  ^
In file included from src/mongo/db/modules/rocks/src/rocks_parameters.h:32:0,
                 from src/mongo/db/modules/rocks/src/rocks_parameters.cpp:32:
src/mongo/db/modules/rocks/src/rocks_engine.h:120:22: error:   by 'virtual bool mongo::RocksEngine::isEphemeral() const' [-Werror=overloaded-virtual]
         virtual bool isEphemeral() const override { return false; }
                      ^
cc1plus: all warnings being treated as errors
scons: *** [build/opt/mongo/db/modules/rocks/src/rocks_parameters.o] Error 1
scons: building terminated because of errors.

**Comment by igorcanadi** [comment]
Can you do this:

cd ~/rocksdb
git log -1
cd ~/mongo-rocks
git log -1

And c/p the output?

Looks like you have older versions of either RocksDB or MongoRocks.

**Comment by igorcanadi** [comment]
Actually I think I just pushed the commit that fixes your issue. Can you re-pull and try again?

**Comment by 15astro** [comment]
@igorcanadi 
This still gives same error as above:
Below are the git logs:
cd rocksdb
git log -1

commit 590e2617ee9204f465770de69dac48947925a3b4
Author: Zuoyan Qin <qinzuoyan@gmail.com>
Date:   Mon May 30 05:26:55 2016 +0800

    fix delete file bug when do checkpoint (#1138)

cd mongo-rocks
git log -1
commit e12140f2daaa85f0a19eb2f3d1a9c70751132c39
Author: Igor Canadi <icanadi@fb.com>
Date:   Fri May 27 09:11:50 2016 -0700

    include <statistics.h>

cd mongo
git log -1
commit 05552b562c7a0b3143a729aaa0838e558dc49b25
Author: David Storch <david.storch@10gen.com>
Date:   Thu Apr 21 16:10:48 2016 -0400

    SERVER-23858 move test of $regex with embedded null to appropriate file
    
    (cherry picked from commit 1a371955e7a93f846a5ddddb19f33d6b270a3991)

**Comment by igorcanadi** [comment]
> This still gives same error as above:

There are two errors above. Is it:
1.  'NUMBER_DB_SEEK' is not a member of 'rocksdb', or
2. mongo::RocksEngine::isEphemeral() const' marked override, but does not override

If it's 2, you need to pull the latest source code from mongo, your mongo branch is too old.

If you're thinking about using this in production, I would recommend pulling both mongo and mongorocks from 3.2 branch instead of master.

**Comment by 15astro** [comment]
I have tried latest source code from mongo i.e, 3.3.6 to avoid issue 2. 
But issue 1,  **'NUMBER_DB_SEEK' is not a member of 'rocksdb'** still appears. 

Along with this, I tried to pull branch 3.2 from mongo and mongo-rocks. 

Still same issue.

**Comment by 15astro** [comment]
@igorcanadi 

I tried the same procedure listed in [doc.](https://github.com/mongodb-partners/mongo-rocks).

I tried git clone --branch 4.1.fb https://github.com/facebook/rocksdb.git to avoid NUMBER_DB_SEEK' is not a member of 'rocksdb' issues.

Repeatedly, The compilation stops with following error:

Compiling build/opt/mongo/db/modules/rocks/src/rocks_server_status.o
src/mongo/db/modules/rocks/src/rocks_server_status.cpp: In member function 'virtual mongo::BSONObj mongo::RocksServerStatusSection::generateSection(mongo::OperationContext*, const mongo::BSONElement&) const':
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:185:14: error: 'NUMBER_DB_SEEK' is not a member of 'rocksdb'
             {rocksdb::NUMBER_DB_SEEK, "num-seeks"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:186:14: error: 'NUMBER_DB_NEXT' is not a member of 'rocksdb'
             {rocksdb::NUMBER_DB_NEXT, "num-forward-iterations"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:187:14: error: 'NUMBER_DB_PREV' is not a member of 'rocksdb'
             {rocksdb::NUMBER_DB_PREV, "num-backward-iterations"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:193:14: error: 'ITER_BYTES_READ' is not a member of 'rocksdb'
             {rocksdb::ITER_BYTES_READ, "bytes-read-iteration"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:197:11: error: could not convert '{{NUMBER_KEYS_WRITTEN, "num-keys-written"}, {NUMBER_KEYS_READ, "num-keys-read"}, {<expression error>, "num-seeks"}, {<expression error>, "num-forward-iterations"}, {<expression error>, "num-backward-iterations"}, {BLOCK_CACHE_MISS, "block-cache-misses"}, {BLOCK_CACHE_HIT, "block-cache-hits"}, {BLOOM_FILTER_USEFUL, "bloom-filter-useful"}, {BYTES_WRITTEN, "bytes-written"}, {BYTES_READ, "bytes-read-point-lookup"}, {<expression error>, "bytes-read-iteration"}, {FLUSH_WRITE_BYTES, "flush-bytes-written"}, {COMPACT_READ_BYTES, "compaction-bytes-read"}, {COMPACT_WRITE_BYTES, "compaction-bytes-written"}}' from '<brace-enclosed initializer list>' to 'const std::vector<std::pair<rocksdb::Tickers, std::basic_string<char> > >'
           };
           ^
scons: *** [build/opt/mongo/db/modules/rocks/src/rocks_server_status.o] Error 1
scons: building terminated because of errors.
build/opt/mongo/db/modules/rocks/src/rocks_server_status.o failed: Error 1


Its reproducible. Can someone help?

**Comment by kadashu** [comment]
Met the same error
mongodb-rocks r3.2.12
mongo r3.2.12
rocksdb v5.2.1

```
Compiling build/opt/mongo/db/modules/rocks/src/rocks_server_status.o
src/mongo/db/modules/rocks/src/rocks_server_status.cpp: In member function 'virtual mongo::BSONObj mongo::RocksServerStatusSection::generateSection(mongo::OperationContext*, const mongo::BSONElement&) const':
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:184:14: error: 'NUMBER_DB_SEEK' is not a member of 'rocksdb'
             {rocksdb::NUMBER_DB_SEEK, "num-seeks"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:185:14: error: 'NUMBER_DB_NEXT' is not a member of 'rocksdb'
             {rocksdb::NUMBER_DB_NEXT, "num-forward-iterations"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:186:14: error: 'NUMBER_DB_PREV' is not a member of 'rocksdb'
             {rocksdb::NUMBER_DB_PREV, "num-backward-iterations"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:192:14: error: 'ITER_BYTES_READ' is not a member of 'rocksdb'
             {rocksdb::ITER_BYTES_READ, "bytes-read-iteration"},
              ^
src/mongo/db/modules/rocks/src/rocks_server_status.cpp:196:11: error: could not convert '{{NUMBER_KEYS_WRITTEN, "num-keys-written"}, {NUMBER_KEYS_READ, "num-keys-read"}, {<expression error>, "num-seeks"}, {<expression error>, "num-forward-iterations"}, {<expression error>, "num-backward-iterations"}, {BLOCK_CACHE_MISS, "block-cache-misses"}, {BLOCK_CACHE_HIT, "block-cache-hits"}, {BLOOM_FILTER_USEFUL, "bloom-filter-useful"}, {BYTES_WRITTEN, "bytes-written"}, {BYTES_READ, "bytes-read-point-lookup"}, {<expression error>, "bytes-read-iteration"}, {FLUSH_WRITE_BYTES, "flush-bytes-written"}, {COMPACT_READ_BYTES, "compaction-bytes-read"}, {COMPACT_WRITE_BYTES, "compaction-bytes-written"}}' from '<brace-enclosed initializer list>' to 'const std::vector<std::pair<rocksdb::Tickers, std::basic_string<char> > >'
           };
           ^
scons: *** [build/opt/mongo/db/modules/rocks/src/rocks_server_status.o] Error 1
scons: building terminated because of errors.
```

**Comment by paomian** [comment]
Maybe your `/usr/local/include` have an old version rocksdb header file, removing it will fix it.

**Comment by kadashu** [comment]
Great. It works.
